services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - /opt/appdata/vaultwarden:/data
    environment:
      - DOMAIN=https://vw.beansrn.com
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
    networks:
      - caddy_default

networks:
  caddy_default:
    external: true
