[[stack]]
name = "traefik-rp5"
description = "Traefik reverse proxy"

[stack.config]
server = "rp5"
file_paths = ["stacks/rp5/infra/traefik/compose.yaml"]
repo = "ryanstuckey0/home-server-komodo"
branch = "main"
environment = """
CF_DNS_API_TOKEN = [[CF_DNS_API_TOKEN]]
TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL = [[EMAIL_FOR_LETSENCRYPT]]
"""

[[stack]]
name = "dns-stack"
description = "Unbound and AdGuard Home DNS servers for LAN and Tailscale"

[stack.config]
server = "rp5"
file_paths = ["stacks/rp5/infra/dns/compose.yaml"]
repo = "ryanstuckey0/home-server-komodo"
branch = "main"