services:
  cup:
    image: ghcr.io/sergi0g/cup:latest
    container_name: cup-rp5
    restart: unless-stopped
    command: -c /config/cup.json serve
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cup.json:/config/cup.json
    networks:
      - caddy_default

networks:
  caddy_default:
    external: true