- Infrastructure:
  - Unifi Dream Router 7:
      href: https://unifi.ui.com
      icon: unifi-dark.png
      widget:
        type: unifi
        url: https://192.168.1.1
        username: "{{HOMEPAGE_VAR_UNIFI_USERNAME}}"
        password: "{{HOMEPAGE_VAR_UNIFI_PASSWORD}}"
        verify-ssl: false
  - AdGuard Home:
      href: https://ag.beansrn.com
      description: DNS filtering & ad blocking
      icon: adguard-home.png
      widget:
        type: adguard
        url: https://ag.beansrn.com
        username: "{{HOMEPAGE_VAR_ADGUARD_USERNAME}}"
        password: "{{HOMEPAGE_VAR_ADGUARD_PASSWORD}}"
  - Komodo:
      href: https://km.beansrn.com
      description: Container orchestration
      icon: komodo.png
      widget:
        type: komodo
        url: https://km.beansrn.com
        key: "{{HOMEPAGE_VAR_KM_KEY}}"
        secret: "{{HOMEPAGE_VAR_KM_SECRET}}"
        showSummary: true # optional, default: false. Takes precedence over showStacks
        showStacks: true # optional, default: false
  - RP5 System:
      description: rp5 system resources
      href: https://glances.rp5.beansrn.com
      icon: raspberry-pi.png
      widget:
        type: glances
        version: 4
        url: http://glances:61208
        metric: info
  - NAS System:
      description: TrueNAS system resources
      href: https://glances.nas.beansrn.com
      icon: truenas.png
      widget:
        type: glances
        version: 4
        url: https://glances.nas.beansrn.com
        metric: info
  - TrueNAS:
      href: https://nas.beansrn.com
      description: NAS storage
      icon: truenas-scale.png
      widget:
        type: truenas
        url: https://nas.beansrn.com
        key: "{{HOMEPAGE_VAR_TRUENAS_API_KEY}}"
        enablePools: true

- Apps:
  - Home Assistant:
      href: https://ha.beansrn.com
      description: Home automation
      icon: home-assistant.png
      widget:
        type: homeassistant
        url: https://ha.beansrn.com
        key: "{{HOMEPAGE_VAR_HA_TOKEN}}"
  - Vaultwarden:
      href: https://vw.beansrn.com
      description: Password manager
      icon: vaultwarden.png
  - Jellyfin:
      href: https://jf.beansrn.com
      description: Media server
      icon: jellyfin.png
      widget:
        type: jellyfin
        url: https://jf.beansrn.com
        key: "{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}"
        enableBlocks: true
