- Infrastructure:
    - AdGuard Home:
        href: https://ag.beansrn.com
        description: DNS filtering & ad blocking
        icon: adguard-home.png
        widget:
          type: adguardhome
          url: https://ag.beansrn.com
          username: "{{HOMEPAGE_VAR_ADGUARD_USERNAME}}"
          password: "{{HOMEPAGE_VAR_ADGUARD_PASSWORD}}"
    - Komodo:
        href: https://km.beansrn.com
        description: Container orchestration
        icon: komodo.png
    - RP5 System:
        description: rp5 system resources
        icon: glances.png
        widget:
          type: glances
          url: http://glances:61208
          metric: info
    - NAS System:
        description: TrueNAS system resources
        icon: glances.png
        widget:
          type: glances
          url: https://glances-nas.beansrn.com
          metric: info
    - TrueNAS:
        href: https://nas.beansrn.com
        description: NAS storage
        icon: truenas-scale.png
        widget:
          type: truenas
          url: https://nas.beansrn.com
          key: "{{HOMEPAGE_VAR_TRUENAS_API_KEY}}"
          enablePools: true

- Apps:
    - Home Assistant:
        href: https://ha.beansrn.com
        description: Home automation
        icon: home-assistant.png
        widget:
          type: homeassistant
          url: https://ha.beansrn.com
          key: "{{HOMEPAGE_VAR_HA_TOKEN}}"
    - Vaultwarden:
        href: https://vw.beansrn.com
        description: Password manager
        icon: vaultwarden.png
    - Jellyfin:
        href: https://jf.beansrn.com
        description: Media server
        icon: jellyfin.png
        widget:
          type: jellyfin
          url: https://jf.beansrn.com
          key: "{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}"
          enableBlocks: true
