services:
  traefik:
    image: traefik:v3.6
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml
    labels:
      - "traefik.routers.traefik.rule=Host(`traefik.beansrn.com`)"
      - "traefik.routers.traefik.entrypoints=web"
      - "traefik.routers.traefik.service=api@internal"
networks:
  default:
    external:
      name: traefik_default