http:
  routers:
    nas:
      rule: "Host(`nas.beansrn.com`)"
      entryPoints:
        - web
      service: nas
  
  services:
    nas:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:81"