api:
  insecure: true

providers:
  docker: {}

entrypoints:
  web:
    address: ":80"

http:
  routers:
    traefik:
      rule: "Host(`traefik.beansrn.com`)"
      entryPoints:
        - web
      service: api@internal
