services:
  unbound:
    image: mvance/unbound-rpi:latest
    container_name: unbound
    restart: unless-stopped
    ports:
      - 5335:53/tcp
      - 5335:53/udp
    volumes:
      - ./unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true