services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances-rp5
    restart: always
    privileged: true
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/os-release:/etc/os-release:ro
      - ./glances.conf:/glances/conf/glances.conf:ro
    environment:
      - "GLANCES_OPT=-w"
    networks:
      - caddy_default

networks:
  caddy_default:
    external: true