[[stack]]
name = "jellyfin"
description = "Jellyfin media server"

[stack.config]
server = "truenas"
file_paths = ["stacks/truenas/apps/jellyfin/compose.yaml"]
repo = "ryanstuckey0/home-server-komodo"
branch = "main"

[[stack]]
name = "glances-nas"
description = "Glances system monitor for TrueNAS"

[stack.config]
server = "truenas"
file_paths = ["stacks/truenas/apps/glances/compose.yaml"]
repo = "ryanstuckey0/home-server-komodo"
branch = "main"

[[stack]]
name = "syncthing-nas"
description = "Syncthing file sync (redundant/backup node for Satisfactory blueprints)"

[stack.config]
server = "truenas"
file_paths = ["stacks/truenas/apps/syncthing/compose.yaml"]
repo = "ryanstuckey0/home-server-komodo"
branch = "main"

[[stack]]
name = "cup-nas"
description = "Docker container update status"

[stack.config]
server = "truenas"
file_paths = ["stacks/truenas/apps/cup/compose.yaml"]
repo = "ryanstuckey0/home-server-komodo"
branch = "main"