[[stack]]
name = "traefik-truenas"
description = "Traefik reverse proxy"

[stack.config]
server = "truenas"
file_paths = ["stacks/truenas/infra/traefik/compose.yaml"]
repo = "ryanstuckey0/home-server-komodo"
branch = "main"
environment = """
CF_DNS_API_TOKEN = [[CF_DNS_API_TOKEN]]
TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL = [[EMAIL_FOR_LETSENCRYPT]]
"""
