http:
  routers:
    truenas:
      rule: "Host(`nas.beansrn.com`)"
      entryPoints:
        - websecure
      service: truenas
      tls: {}

  services:
    truenas:
      loadBalancer:
        servers:
          - url: "http://nas.beansrn.com:81"
