services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=home.beansrn.com
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - HOMEPAGE_VAR_ADGUARD_USERNAME=${HOMEPAGE_VAR_ADGUARD_USERNAME}
      - HOMEPAGE_VAR_ADGUARD_PASSWORD=${HOMEPAGE_VAR_ADGUARD_PASSWORD}
      - HOMEPAGE_VAR_HA_TOKEN=${HOMEPAGE_VAR_HA_TOKEN}
      - HOMEPAGE_VAR_TRUENAS_API_KEY=${HOMEPAGE_VAR_TRUENAS_API_KEY}
      - HOMEPAGE_VAR_JELLYFIN_API_KEY=${HOMEPAGE_VAR_JELLYFIN_API_KEY}
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
      - caddy_default

  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: unless-stopped
    privileged: true
    pid: host
    environment:
      - GLANCES_OPT=-w --disable-webui
    volumes:
      - ./glances.conf:/glances/conf/glances.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default

networks:
  default: {}
  caddy_default:
    external: true
