services:
  caddy:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /mnt/pool01/appdata/caddy:/data
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    name: caddy_default
